from __future__ import annotations

import io
import zipfile
from datetime import date
from typing import Any

from app.services.docx_exporter import DocxExportError, report_to_docx
from app.services.pdf_exporter import PdfExportError, report_to_pdf
from app.services.exporters import report_to_csv, serialize_report, structure_annotations_to_csv

import json


def report_to_zip(report: dict[str, Any]) -> bytes:
    """Bundle a comprehensive ZIP package for the report.

    Contents:
      report.docx
      report.json
      report.csv
      structure_annotations.csv  (if secondary_structure_panel available)
      README.txt
    """
    protein = report["protein"]
    variant = report["variant"]
    prefix = f"Report_{protein.accession}_{variant.short_notation.replace(' ', '_')}"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # PDF report (primary)
        try:
            pdf_bytes = report_to_pdf(report)
            zf.writestr(f"{prefix}/report.pdf", pdf_bytes)
        except (PdfExportError, Exception) as exc:
            zf.writestr(f"{prefix}/pdf_error.txt", f"PDF could not be generated: {exc}")

        # Word document
        try:
            docx_bytes = report_to_docx(report)
            zf.writestr(f"{prefix}/report.docx", docx_bytes)
        except (DocxExportError, Exception) as exc:
            zf.writestr(f"{prefix}/docx_error.txt", f"Word document could not be generated: {exc}")

        # JSON
        try:
            json_data = json.dumps(serialize_report(report), indent=2, default=str)
            zf.writestr(f"{prefix}/report.json", json_data)
        except Exception:
            pass

        # Main CSV
        try:
            csv_data = report_to_csv(report)
            zf.writestr(f"{prefix}/report.csv", csv_data)
        except Exception:
            pass

        # Structure annotations CSV
        if report.get("secondary_structure_panel"):
            try:
                sa_csv = structure_annotations_to_csv(report)
                zf.writestr(f"{prefix}/structure_annotations.csv", sa_csv)
            except Exception:
                pass

        # README
        readme = _build_readme(report)
        zf.writestr(f"{prefix}/README.txt", readme)

    return buf.getvalue()


def _build_readme(report: dict[str, Any]) -> str:
    protein = report["protein"]
    variant = report["variant"]
    today = date.today().isoformat()
    sp = report.get("stability_panel")
    af = report.get("alphafold_panel")

    lines = [
        "Protein Mutation Analysis Report — Export Bundle",
        "=" * 50,
        f"Generated: {today}",
        "",
        "PROTEIN",
        f"  Accession : {protein.accession}",
        f"  Entry     : {protein.entry_name or '—'}",
        f"  Gene      : {protein.gene_symbol or '—'}",
        f"  Name      : {protein.protein_name or '—'}",
        f"  Organism  : {protein.organism_name or '—'}",
        f"  Length    : {protein.length} aa",
        "",
        "VARIANT",
        f"  Submitted : {variant.original_text}",
        f"  Normalized: {variant.short_notation}",
        f"  HGVS      : {variant.hgvs_protein or '—'}",
        f"  Change    : {variant.wild_type} → {variant.mutant} at position {variant.position}",
        "",
    ]

    if sp:
        lines += [
            "STABILITY PREDICTION",
            f"  ΔΔG estimate : {sp['ddg_estimate']:+.2f} kcal/mol ({sp['ddg_label']})",
            f"  BLOSUM62     : {sp['blosum62_score']} — {sp['blosum62_interpretation']}",
            f"  SIFT-proxy   : {sp['sift_proxy']} ({sp['sift_tolerance']})",
            "",
        ]

    if af and af.get("plddt_available"):
        lines += [
            "ALPHAFOLD",
            f"  Mean pLDDT   : {af.get('mean_plddt', '—')} ({af.get('mean_plddt_label', '—')})",
            "",
        ]

    lines += [
        "FILES IN THIS BUNDLE",
        "  report.pdf                  — Full PDF report with charts and tables",
        "  report.docx                 — Full Word document report with charts",
        "  report.json                 — Complete structured data (JSON)",
        "  report.csv                  — Core protein/variant/metrics data (CSV)",
        "  structure_annotations.csv  — Per-residue PSIPRED data (if available)",
        "",
        "DISCLAIMER",
        "  This report is generated by the Protein Mutation Workbench (academic prototype).",
        "  ΔΔG estimates are empirical approximations, not physics-based calculations.",
        "  AlphaFold pLDDT and AlphaMissense data are sourced from the EBI AlphaFold database.",
        "  Always verify findings with experimental data before clinical or research use.",
    ]

    return "\n".join(lines)
